version: '3.1'

services:

  wordpress:
    image: wordpress:php8.3-apache
    #container_name: wordpress
    restart: unless-stopped
    ports:
      - ${WEB_SERVER_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:3306
      WORDPRESS_DB_USER: ${MYSQL_DATABASE_USER_NAME}
      WORDPRESS_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE_NAME}
      WORDPRESS_DB_ROOT_PASSWORD: ${MYSQL_DATABASE_ROOT_PASSWORD}
   
    volumes:
      - /data/roy/wordpress/${VOLUME_WORDPRESS}-test:/var/www/html

  ${DB_NAME}_db:
    image: jc21/mariadb-aria:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_DATABASE_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_ROOT_PASSWORD}
 #  networks:
 #     - wordpress     
    volumes:
      - /root/json/data/${VOLUME_DB}-db_test:/var/lib/mysql



networks:
  default:
    external: true
    name: npm_default